Enforce PPA on Ubuntu

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11,6 +11,7 @@ PKG_DEB_NAME="libgit2-dev"
 PKG_RPM_NAME="libgit2-devel"
 PKG_BREW_NAME="libgit2"
 PKG_TEST_HEADER="<git2.h>"
+PKG_TEST_FILE="tools/version.c"
 PKG_LIBS="-lgit2"
 PKG_CFLAGS=""
 
@@ -55,34 +56,48 @@ echo "#include $PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E 
 
 # Customize the error
 if [ $? -ne 0 ]; then
+  echo "------------------------- ANTICONF ERROR ---------------------------"
+  echo "Configuration failed because $PKG_CONFIG_NAME was not found. Try installing:"
+  echo " * brew: $PKG_BREW_NAME (MacOS)"
+  echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
+  echo " * rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)"
+  echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
+  echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
+  echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
+  echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
+  echo "--------------------------------------------------------------------"
+  exit 1;
+fi
+
+# Write to Makevars
+sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" src/Makevars.in > src/Makevars
+
+# Allow for skipping test
+if [ "$SKIP_LIBGIT2_VERSION_TEST" ]; then
+  exit 0
+fi
+
+# Test version of libgit2
+${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E ${PKG_TEST_FILE} >/dev/null 2>&1
+
+# On Ubuntu we enforce using the PPA
+if [ $? -ne 0 ]; then
   lsb_release -c 2>/dev/null | grep -E 'trusty|xenial' 2>/dev/null
   if [ $? -eq 0 ]; then
     echo "------------------------- ANTICONF ERROR ---------------------------"
-    echo "Configuration failed because $PKG_CONFIG_NAME is not installed."
-    echo "Please install it from the following PPA (Ubuntu Trusty or Xenial):"
+    echo "Configuration failed because $PKG_CONFIG_NAME is too old."
+    echo "Please install it from the following PPA for Ubuntu Trusty or Xenial:"
     echo ""
     echo "  sudo add-apt-repository ppa:opencpu/libgit2"
     echo "  sudo apt-get update"
     echo "  sudo apt-get install libssh2-1-dev libgit2-dev"
     echo ""
     echo "--------------------------------------------------------------------"
+    exit 1
   else
-    echo "------------------------- ANTICONF ERROR ---------------------------"
-    echo "Configuration failed because $PKG_CONFIG_NAME was not found. Try installing:"
-    echo " * brew: $PKG_BREW_NAME (MacOS)"
-    echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
-    echo " * rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)"
-    echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
-    echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
-    echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
-    echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
-    echo "--------------------------------------------------------------------"
+    echo "WARNING: your version of libgit2 is really old! HTTPS / SSH might not work"
   fi
-  exit 1;
 fi
-
-# Write to Makevars
-sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" src/Makevars.in > src/Makevars
 
 # Success
 echo "Configuration OK!"
