Hint at PPA in configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -51,19 +51,31 @@ echo "Using PKG_CFLAGS=$PKG_CFLAGS"
 echo "Using PKG_LIBS=$PKG_LIBS"
 
 # Test configuration
-echo "#include $PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - >/dev/null 2>&1 || R_CONFIG_ERROR=1;
+echo "#include $PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - >/dev/null 2>&1
 
 # Customize the error
-if [ $R_CONFIG_ERROR ]; then
-  echo "------------------------- ANTICONF ERROR ---------------------------"
-  echo "Configuration failed because $PKG_CONFIG_NAME was not found. Try installing:"
-  echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
-  echo " * rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)"
-  echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
-  echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
-  echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
-  echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
-  echo "--------------------------------------------------------------------"
+if [ $? -ne 0 ]; then
+  lsb_release -c 2>/dev/null | grep -E 'trusty|xenial' 2>/dev/null
+  if [ $? -eq 0 ]; then
+    echo "------------------------- ANTICONF ERROR ---------------------------"
+    echo "Configuration failed because $PKG_CONFIG_NAME is not installed"
+    echo "Please install it from the PPA (Ubuntu Trusty or Xenial)"
+    echo "  sudo add-apt-repository ppa:opencpu/libgit2"
+    echo "  sudo apt-get update"
+    echo "  sudo apt-get install libssh2-dev libgit2-dev"
+    echo "--------------------------------------------------------------------"
+  else
+    echo "------------------------- ANTICONF ERROR ---------------------------"
+    echo "Configuration failed because $PKG_CONFIG_NAME was not found. Try installing:"
+    echo " * brew: $PKG_BREW_NAME (MacOS)"
+    echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
+    echo " * rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)"
+    echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
+    echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
+    echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
+    echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
+    echo "--------------------------------------------------------------------"
+  fi
   exit 1;
 fi
 
